"""add wechat appid

Revision ID: 8bc9261ad93d
Revises: d0eea4d28d19
Create Date: 2024-12-04 09:51:25.541963

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8bc9261ad93d'
down_revision: Union[str, None] = 'd0eea4d28d19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('wechat_app_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'wechat_app_id')
    # ### end Alembic commands ###
