"""remove username1 field from user model

Revision ID: d0eea4d28d19
Revises: f370f3a51174
Create Date: 2024-12-03 20:11:03.113708

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'd0eea4d28d19'
down_revision: Union[str, None] = 'f370f3a51174'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username1')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username1', mysql.VARCHAR(length=255), nullable=True))
    # ### end Alembic commands ###
