"""user model add a field username1

Revision ID: d8e0aaed5e65
Revises: c38ae996faa6
Create Date: 2024-12-03 19:37:33.547444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8e0aaed5e65'
down_revision: Union[str, None] = 'c38ae996faa6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username1', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'username1')
    # ### end Alembic commands ###
